[[example]]
name = 'pgdemo1'

[dependencies]
num-traits = '0.2.12'
rand = '0.7.3'
rand_distr = '0.3.0'
ndarray = {git="https://github.com/astrojhgu/ndarray.git"}

[package]
authors = ['GU Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'rspgplot'
version = '0.1.0'
